// data.js - لینک‌های اشتراک‌های رایگان
const subscriptionsData = {
    "ایکس ری": {
        "config fetcher": "https://raw.githubusercontent.com/10ium/multi-proxy-config-fetcher/refs/heads/main/configs/proxy_configs.txt",
        "HiNVPN hysteria2": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/normal/hysteria2",
        "HiNVPN hysteria": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/normal/hysteria",
        "HiNVPN tuic": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/normal/tuic",
        "HiNVPN trojan": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/normal/trojan",
        "HiNVPN ss": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/normal/ss",
        "HiNVPN vless": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/normal/vless",
        "HiNVPN vmess": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/normal/vmess",
        "HiNVPN mix": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/normal/mix",
        "V2Hub merged": "https://raw.githubusercontent.com/10ium/V2Hub3/main/merged",
        "V2Hub vmess": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Normal/vmess",
        "V2Hub vless": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Normal/vless",
        "V2Hub reality": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Normal/reality",
        "V2Hub trojan": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Normal/trojan",
        "V2Hub shadowsocks": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Normal/shadowsocks",
        "Aggregator": "https://raw.githubusercontent.com/10ium/V2RayAggregator/refs/heads/master/Eternity.txt",
        "CollectorLite vmess": "https://raw.githubusercontent.com/10ium/V2rayCollectorLite/main/vmess_iran.txt",
        "CollectorLite ss": "https://raw.githubusercontent.com/10ium/V2rayCollectorLite/main/ss_iran.txt",
        "CollectorLite trojan": "https://raw.githubusercontent.com/10ium/V2rayCollectorLite/main/trojan_iran.txt",
        "CollectorLite vless": "https://raw.githubusercontent.com/10ium/V2rayCollectorLite/main/vless_iran.txt",
        "CollectorLite mixed": "https://raw.githubusercontent.com/10ium/V2rayCollectorLite/main/mixed_iran.txt",
        "Collector vmess": "https://raw.githubusercontent.com/10ium/V2rayCollector/main/vmess_iran.txt",
        "Collector ss": "https://raw.githubusercontent.com/10ium/V2rayCollector/main/ss_iran.txt",
        "Collector trojan": "https://raw.githubusercontent.com/10ium/V2rayCollector/main/trojan_iran.txt",
        "Collector vless": "https://raw.githubusercontent.com/10ium/V2rayCollector/main/vless_iran.txt",
        "Collector mixed": "https://raw.githubusercontent.com/10ium/V2rayCollector/main/mixed_iran.txt",
        "V2ray Config All": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/All_Configs_Sub.txt",
        "Rayan Config": "https://raw.githubusercontent.com/Rayan-Config/C-Sub/refs/heads/main/configs/proxy.txt",
        "roosterkid": "https://raw.githubusercontent.com/roosterkid/openproxylist/refs/heads/main/V2RAY_RAW.txt",
        "maimengmeng valid content": "https://raw.githubusercontent.com/maimengmeng/mysub/refs/heads/main/valid_content.txt",
        "maimengmeng valid content all": "https://raw.githubusercontent.com/maimengmeng/mysub/refs/heads/main/valid_content_all.txt",
        "MahsaNetConfigTopic": "https://raw.githubusercontent.com/MahsaNetConfigTopic/config/refs/heads/main/xray_final.txt",
        "Freedom Guard Finder mixed": "https://raw.githubusercontent.com/Freedom-Guard-Builder/Freedom-Finder/refs/heads/main/out/mixed_configs.txt",
        "Freedom Guard Finder configs": "https://raw.githubusercontent.com/Freedom-Guard-Builder/Freedom-Finder/refs/heads/main/out/configs.txt",
        "Freedom Guard Finder raw_all": "https://raw.githubusercontent.com/Freedom-Guard-Builder/Freedom-Finder/refs/heads/main/out/raw_all.txt",
        "ebrasha All Protocols Combined": "https://raw.githubusercontent.com/ebrasha/free-v2ray-public-list/refs/heads/main/all_extracted_configs.txt",
        "ebrasha Lightweight All-in-One": "https://raw.githubusercontent.com/ebrasha/free-v2ray-public-list/refs/heads/main/V2Ray-Config-By-EbraSha.txt",
        "ebrasha Full-size All-in-One": "https://raw.githubusercontent.com/ebrasha/free-v2ray-public-list/refs/heads/main/V2Ray-Config-By-EbraSha-All-Type.txt",
        "ebrasha ss": "https://raw.githubusercontent.com/ebrasha/free-v2ray-public-list/refs/heads/main/ss_configs.txt",
        "ebrasha ssr": "https://raw.githubusercontent.com/ebrasha/free-v2ray-public-list/refs/heads/main/ssr_configs.txt",
        "ebrasha trojan": "https://raw.githubusercontent.com/ebrasha/free-v2ray-public-list/refs/heads/main/trojan_configs.txt",
        "ebrasha vless": "https://raw.githubusercontent.com/ebrasha/free-v2ray-public-list/refs/heads/main/vless_configs.txt",
        "ebrasha vmess": "https://raw.githubusercontent.com/ebrasha/free-v2ray-public-list/refs/heads/main/vmess_configs.txt",
        "F0rc3Run Mix": "https://raw.githubusercontent.com/F0rc3Run/F0rc3Run/refs/heads/main/splitted-by-country/XX.txt",
        "F0rc3Run hysteria2": "https://raw.githubusercontent.com/F0rc3Run/F0rc3Run/refs/heads/main/splitted-by-protocol/hysteria2/hysteria2.txt",
        "F0rc3Run ss": "https://raw.githubusercontent.com/F0rc3Run/F0rc3Run/refs/heads/main/splitted-by-protocol/ss/ss.txt",
        "F0rc3Run trojan": "https://raw.githubusercontent.com/F0rc3Run/F0rc3Run/refs/heads/main/splitted-by-protocol/trojan/trojan.txt",
        "F0rc3Run tuic": "https://raw.githubusercontent.com/F0rc3Run/F0rc3Run/refs/heads/main/splitted-by-protocol/tuic/tuic.txt",
        "F0rc3Run vmess": "https://raw.githubusercontent.com/F0rc3Run/F0rc3Run/refs/heads/main/splitted-by-protocol/vmess/vmess.txt",
        "F0rc3Run vless": "https://raw.githubusercontent.com/F0rc3Run/F0rc3Run/refs/heads/main/splitted-by-protocol/vless/vless_part1.txt",
        "code3 dev vip": "https://raw.githubusercontent.com/code3-dev/v-data/refs/heads/main/vip",
        "darkvpnapp CloudflarePlus proxy": "https://raw.githubusercontent.com/darkvpnapp/CloudflarePlus/refs/heads/main/proxy",
        "darkvpnapp IRDevs": "https://raw.githubusercontent.com/darkvpnapp/IRDevs/refs/heads/main/index.html",
        "darkvpnapp CloudflarePlus cdn": "https://raw.githubusercontent.com/darkvpnapp/CloudflarePlus/refs/heads/main/cdn",
        "darkvpnapp cslab": "https://raw.githubusercontent.com/darkvpnapp/cslab/refs/heads/main/index.html",
        "darkvpnapp safar724": "https://raw.githubusercontent.com/darkvpnapp/safar724/refs/heads/main/api",
        "darkvpnapp Cloud2": "https://raw.githubusercontent.com/darkvpnapp/Cloud2/refs/heads/main/aparatapi",
        "4n0nymou3 config fetcher": "https://github.com/4n0nymou3/multi-proxy-config-fetcher/raw/refs/heads/main/configs/proxy_configs.txt",
        "amiralter lite": "https://sub.amiralter.com/config-lite",
        "amiralter config": "https://sub.amiralter.com/config",
        "Telegram Eag1e YT": "https://raw.githubusercontent.com/Created-By/Telegram-Eag1e_YT/refs/heads/main/%40Eag1e_YT",
        "arshiacomplus robinhood": "https://raw.githubusercontent.com/arshiacomplus/robinhood-v1-v2-v3ray/refs/heads/main/conf.txt",
        "arshiacomplus vmess": "https://raw.githubusercontent.com/arshiacomplus/v2rayExtractor/refs/heads/main/vmess.html",
        "arshiacomplus ss": "https://raw.githubusercontent.com/arshiacomplus/v2rayExtractor/refs/heads/main/ss.html",
        "arshiacomplus trojan": "https://raw.githubusercontent.com/arshiacomplus/v2rayExtractor/refs/heads/main/trojan.html",
        "arshiacomplus vless": "https://raw.githubusercontent.com/arshiacomplus/v2rayExtractor/refs/heads/main/vless.html",
        "arshiacomplus mix": "https://raw.githubusercontent.com/arshiacomplus/v2rayExtractor/refs/heads/main/mix/sub.html"
    },
    
    "ایکس ری بیس۶۴": {
        "config fetcher": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium_proxy_configs.txt",
        "HiN VPN hysteria2": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/base64/hysteria2",
        "HiN VPN hysteria": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/base64/hysteria",
        "HiN VPN tuic": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/base64/tuic",
        "HiN VPN trojan": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/base64/trojan",
        "HiN VPN ss": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/base64/ss",
        "HiN VPN vless": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/base64/vless",
        "HiN VPN vmess": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/base64/vmess",
        "HiN VPN mix": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/base64/mix",
        "MahsaFreeConfig mci 1": "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mci/sub_1.txt",
        "MahsaFreeConfig mci 2": "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mci/sub_2.txt",
        "MahsaFreeConfig mci 3": "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mci/sub_3.txt",
        "MahsaFreeConfig mci 4": "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mci/sub_4.txt",
        "MahsaFreeConfig mtn 1": "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mtn/sub_1.txt",
        "MahsaFreeConfig mtn 2": "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mtn/sub_2.txt",
        "MahsaFreeConfig mtn 3": "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mtn/sub_3.txt",
        "MahsaFreeConfig mtn 4": "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mtn/sub_4.txt",
        "V2Hub merged": "https://raw.githubusercontent.com/10ium/V2Hub3/main/merged_base64",
        "V2Hub vmess": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Base64/vmess",
        "V2Hub vless": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Base64/vless",
        "V2Hub reality": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Base64/reality",
        "V2Hub trojan": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Base64/trojan",
        "V2Hub shadowsocks": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Base64/shadowsocks",
        "Aggregator": "https://raw.githubusercontent.com/10ium/V2RayAggregator/refs/heads/master/Eternity",
        "CollectorLite vmess": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium_vmess_iran.txt",
        "CollectorLite ss": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium_ss_iran.txt",
        "CollectorLite trojan": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium_trojan_iran.txt",
        "CollectorLite vless": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium_vless_iran.txt",
        "CollectorLite mixed": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium_mixed_iran.txt",
        "Collector mixed": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium-V2rayCollector-mixed.txt",
        "Collector ss": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium-V2rayCollector-ss.txt",
        "Collector trojan": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium-V2rayCollector-trojan.txt",
        "Collector vless": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium-V2rayCollector-vless.txt",
        "Collector vmess": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium-V2rayCollector-vmess.txt",
        "V2ray Config vmess": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/Splitted-By-Protocol/vmess.txt",
        "V2ray Config vless": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/Splitted-By-Protocol/vless.txt",
        "V2ray Config trojan": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/Splitted-By-Protocol/trojan.txt",
        "V2ray Config ss": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/Splitted-By-Protocol/ss.txt",
        "V2ray Config ssr": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/Splitted-By-Protocol/ssr.txt",
        "V2ray Config tuic": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/Splitted-By-Protocol/tuic.txt",
        "V2ray Config hysteria2": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/Splitted-By-Protocol/hysteria2.txt",
        "rayan proxy": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/refs/heads/main/shuffled_outputs/rayan_proxy.txt",
        "roosterkid": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/refs/heads/main/shuffled_outputs/roosterkid_v2ray.txt",
        "shadowmere.xyz": "https://shadowmere.xyz/api/b64sub",
        "maimengmeng": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/refs/heads/main/shuffled_outputs/maimengmeng.txt",
        "maimengmeng AnyTLS": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/refs/heads/main/shuffled_outputs/maimengmeng_AnyTLS.txt",
        "itsyebekhe PSG mix": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/mix",
        "itsyebekhe PSG reality": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/reality",
        "itsyebekhe PSG reality domain": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/reality_domain",
        "itsyebekhe PSG reality ipv4": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/reality_ipv4",
        "itsyebekhe PSG reality ipv6": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/reality_ipv6",
        "itsyebekhe PSG xhttp": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/xhttp",
        "itsyebekhe PSG xhttp domain": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/xhttp_domain",
        "itsyebekhe PSG xhttp ipv4": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/xhttp_ipv4",
        "itsyebekhe PSG ss": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/ss",
        "itsyebekhe PSG ss domain": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/ss_domain",
        "itsyebekhe PSG ss ipv4": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/ss_ipv4",
        "itsyebekhe PSG ss ipv6": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/ss_ipv6",
        "itsyebekhe PSG trojan": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/trojan",
        "itsyebekhe PSG trojan domain": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/trojan_domain",
        "itsyebekhe PSG trojan ipv4": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/trojan_ipv4",
        "itsyebekhe PSG trojan ipv6": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/trojan_ipv6",
        "itsyebekhe PSG vless": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/vless",
        "itsyebekhe PSG vless domain": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/vless_domain",
        "itsyebekhe PSG vless ipv4": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/vless_ipv4",
        "itsyebekhe PSG vless ipv6": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/vless_ipv6",
        "itsyebekhe PSG tuic": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/tuic",
        "itsyebekhe PSG tuic ipv4": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/tuic_ipv4",
        "itsyebekhe PSG tuic ipv6": "https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/tuic_ipv6",
        "10ium V2ray Config_All cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/10ium_V2ray_Config_All_cloudflare.txt",
        "10ium V2ray Config_vmess cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/10ium_V2ray_Config_vmess_cloudflare.txt",
        "10ium V2ray Config_vless cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/10ium_V2ray_Config_vless_cloudflare.txt",
        "10ium V2ray Config_trojan cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/10ium_V2ray_Config_trojan_cloudflare.txt",
        "10ium V2ray Config_ss cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/10ium_V2ray_Config_ss_cloudflare.txt",
        "10ium telegram configs collector cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/10ium_telegram_configs_collector_cloudflare.txt",
        "10ium V2ray HiNVPN mix cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/10ium_V2ray_HiNVPN_mix_cloudflare.txt",
        "10ium V2Hub merged cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/10ium_V2Hub_merged_cloudflare.txt",
        "10ium fetcher cloudflare.txt": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/10ium_fetcher_cloudflare.txt",
        "10ium CollectorLite Config mixed cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/10ium_CollectorLite_Config_mixed_cloudflare.txt",
        "10ium Collector mixed cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/10ium_Collector_mixed_cloudflare.txt",
        "maimengmeng cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/maimengmeng_cloudflare.txt",
        "roosterkid cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/roosterkid_cloudflare.txt",
        "itsyebekhe PSG xhttp mix cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/itsyebekhe PSG xhttp mix_cloudflare.txt",
        "itsyebekhe PSG xhttp trojan cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/itsyebekhe PSG xhttp trojan_cloudflare.txt",
        "mahsanet mci2 cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/mahsanet_mci2_cloudflare.txt",
        "mahsanet mci3 cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/mahsanet_mci3_cloudflare.txt",
        "mahsanet mtn2 cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/mahsanet_mtn2_cloudflare.txt",
        "mahsanet mtn3 cloudflare": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/main/shuffled_outputs/mahsanet_mtn3_cloudflare.txt",
        "Juicity - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/protocols/juicity",
        "Juicity - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/protocols/juicity",
        "Juicity - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/protocols/juicity",
        "Hysteria - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/protocols/hysteria",
        "Hysteria - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/protocols/hysteria",
        "Hysteria - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/protocols/hysteria",
        "Tuic - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/protocols/tuic",
        "Tuic - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/protocols/tuic",
        "Tuic - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/protocols/tuic",
        "Reality - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/protocols/reality",
        "Reality - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/protocols/reality",
        "Reality - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/protocols/reality",
        "Vless - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/protocols/vless",
        "Vless - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/protocols/vless",
        "Vless - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/protocols/vless",
        "Vmess - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/protocols/vmess",
        "Vmess - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/protocols/vmess",
        "Vmess - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/protocols/vmess",
        "Trojan - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/protocols/trojan",
        "Trojan - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/protocols/trojan",
        "Trojan - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/protocols/trojan",
        "Shadowsocks - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/protocols/shadowsocks",
        "Shadowsocks - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/protocols/shadowsocks",
        "Shadowsocks - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/protocols/shadowsocks",
        "Mixed Type - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/splitted/mixed",
        "Mixed Type - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/splitted/channels",
        "Mixed Type - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/splitted/subscribe",
        "Google Remote Procedure Call (GRPC) - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/networks/grpc",
        "Google Remote Procedure Call (GRPC) - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/networks/grpc",
        "Google Remote Procedure Call (GRPC) - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/networks/grpc",
        "Hypertext Transfer Protocol (HTTP) - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/networks/http",
        "Hypertext Transfer Protocol (HTTP) - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/networks/http",
        "Hypertext Transfer Protocol (HTTP) - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/networks/http",
        "WebSocket Protocol (WS) - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/networks/ws",
        "WebSocket Protocol (WS) - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/networks/ws",
        "WebSocket Protocol (WS) - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/networks/ws",
        "Transmission Control Protocol (TCP) - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/networks/tcp",
        "Transmission Control Protocol (TCP) - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/networks/tcp",
        "Transmission Control Protocol (TCP) - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/networks/tcp",
        "Transport Layer Security (TLS) - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/security/tls",
        "Transport Layer Security (TLS) - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/security/tls",
        "Transport Layer Security (TLS) - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/security/tls",
        "Non Transport Layer Security (Non-TLS) - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/security/non-tls",
        "Non Transport Layer Security (Non-TLS) - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/security/non-tls",
        "Non Transport Layer Security (Non-TLS) - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/security/non-tls",
        "Internet Protocol Version 4 (IPV4) - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/layers/ipv4",
        "Internet Protocol Version 4 (IPV4) - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/layers/ipv4",
        "Internet Protocol Version 4 (IPV4) - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/layers/ipv4",
        "Internet Protocol Version 6 (IPV6) - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/layers/ipv6",
        "Internet Protocol Version 6 (IPV6) - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/layers/ipv6",
        "Internet Protocol Version 6 (IPV6) - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/layers/ipv6",
        "آلبانی 🇦🇱": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/al/mixed",
        "آرژانتین 🇦🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ar/mixed",
        "ارمنستان 🇦🇲": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/am/mixed",
        "استرالیا 🇦🇺": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/au/mixed",
        "اتریش 🇦🇹": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/at/mixed",
        "بحرین 🇧🇭": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/bh/mixed",
        "بلاروس 🇧🇾": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/by/mixed",
        "بلژیک 🇧🇪": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/be/mixed",
        "بولیوی 🇧🇴": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/bo/mixed",
        "برزیل 🇧🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/br/mixed",
        "بلغارستان 🇧🇬": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/bg/mixed",
        "کانادا 🇨🇦": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ca/mixed",
        "چین 🇨🇳": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/cn/mixed",
        "کلمبیا 🇨🇴": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/co/mixed",
        "کرواسی 🇭🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/hr/mixed",
        "قبرس 🇨🇾": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/cy/mixed",
        "چک 🇨🇿": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/cz/mixed",
        "دانمارک 🇩🇰": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/dk/mixed",
        "اکوادور 🇪🇨": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ec/mixed",
        "استونی 🇪🇪": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ee/mixed",
        "فنلاند 🇫🇮": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/fi/mixed",
        "فرانسه 🇫🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/fr/mixed",
        "آلمان 🇩🇪": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/de/mixed",
        "جبل‌الطارق 🇬🇮": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/gi/mixed",
        "یونان 🇬🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/gr/mixed",
        "گواتمالا 🇬🇹": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/gt/mixed",
        "هنگ کنگ 🇭🇰": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/hk/mixed",
        "مجارستان 🇭🇺": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/hu/mixed",
        "ایسلند 🇮🇸": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/is/mixed",
        "هند 🇮🇳": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/in/mixed",
        "اندونزی 🇮🇩": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/id/mixed",
        "ایران 🇮🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ir/mixed",
        "عراق 🇮🇶": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/iq/mixed",
        "ایرلند 🇮🇪": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ie/mixed",
        "اسرائیل 🇮🇱": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/il/mixed",
        "ایتالیا 🇮🇹": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/it/mixed",
        "ژاپن 🇯🇵": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/jp/mixed",
        "اردن 🇯🇴": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/jo/mixed",
        "قزاقستان 🇰🇿": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/kz/mixed",
        "کره جنوبی 🇰🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/kr/mixed",
        "لتونی 🇱🇻": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/lv/mixed",
        "لیتوانی 🇱🇹": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/lt/mixed",
        "لوکزامبورگ 🇱🇺": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/lu/mixed",
        "مالزی 🇲🇾": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/my/mixed",
        "مالت 🇲🇹": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/mt/mixed",
        "مکزیک 🇲🇽": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/mx/mixed",
        "مولداوی 🇲🇩": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/md/mixed",
        "هلند 🇳🇱": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/nl/mixed",
        "نیوزیلند 🇳🇿": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/nz/mixed",
        "مقدونیه شمالی 🇲🇰": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/mk/mixed",
        "نروژ 🇳🇴": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/no/mixed",
        "نامشخص ❓": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/na/mixed",
        "عمان 🇴🇲": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/om/mixed",
        "پاکستان 🇵🇰": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/pk/mixed",
        "پاراگوئه 🇵🇾": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/py/mixed",
        "پرو 🇵🇪": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/pe/mixed",
        "فیلیپین 🇵🇭": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ph/mixed",
        "لهستان 🇵🇱": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/pl/mixed",
        "پرتغال 🇵🇹": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/pt/mixed",
        "پورتوریکو 🇵🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/pr/mixed",
        "رومانی 🇷🇴": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ro/mixed",
        "روسیه 🇷🇺": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ru/mixed",
        "صربستان 🇷🇸": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/rs/mixed",
        "سیشل 🇸🇨": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/sc/mixed",
        "سنگاپور 🇸🇬": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/sg/mixed",
        "اسلواکی 🇸🇰": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/sk/mixed",
        "اسلوونی 🇸🇮": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/si/mixed",
        "آفریقای جنوبی 🇿🇦": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/za/mixed",
        "اسپانیا 🇪🇸": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/es/mixed",
        "سوئد 🇸🇪": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/se/mixed",
        "سوئیس 🇨🇭": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ch/mixed",
        "تایوان 🇹🇼": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/tw/mixed",
        "تایلند 🇹🇭": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/th/mixed",
        "ترکیه 🇹🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/tr/mixed",
        "اوکراین 🇺🇦": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ua/mixed",
        "امارات متحده عربی 🇦🇪": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ae/mixed",
        "بریتانیا 🇬🇧": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/gb/mixed",
        "ایالات متحده 🇺🇸": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/us/mixed",
        "ویتنام 🇻🇳": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/vn/mixed"
    },
    
    "میهومو (کلش متا)": {
        "Multi Country Rule Plus": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/Multi__Country__RulePlus.yaml",
        "Multi Country No Rule": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/Multi__Country__NoRule.yaml",
        "WARP+Ainita": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/WARP%20%2B%20Ainita_%5BMulti-Profile%5D_%5BFull%5D.yaml",
        "countries Rule Plus": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/Nearby_countries__RulePlus.yaml",
        "countries No Rule": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/Nearby_countries__NoRule.yaml",
        "telegram configs collector": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/telegram-configs-collector.yaml",
        "config fetcher": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/10ium/multi-proxy-config-fetcher.yaml",
        "Mahsa Free Config mci": "https://raw.githubusercontent.com/10ium/Vpnclashfa/refs/heads/main/free-mihomo-sub/MahsaFreeConfig-mci.yaml",
        "Mahsa Free Config mtn": "https://raw.githubusercontent.com/10ium/Vpnclashfa/refs/heads/main/free-mihomo-sub/MahsaFreeConfig-mtn.yaml",
        "Mahsa Free Config mix": "https://raw.githubusercontent.com/10ium/Vpnclashfa/refs/heads/main/free-mihomo-sub/MahsaFreeConfig-mix.yaml",
        "V2Hub reality": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/10ium/V2Hub3_reality.yaml",
        "V2Hub shadowsocks": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/10ium/V2Hub3_shadowsocks.yaml",
        "V2Hub trojan": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/10ium/V2Hub3_trojan.yaml",
        "V2Hub vmess": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/10ium/V2Hub3_vmess.yaml",
        "Aggregator": "https://raw.githubusercontent.com/10ium/V2RayAggregator/refs/heads/master/Eternity.yml",
        "CollectorLite ss": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/10ium/ss_iran.yaml",
        "CollectorLite trojan": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/10ium/trojan_iran.yaml",
        "CollectorLite vmess": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/10ium/vmess_iran.yaml",
        "MahsaNetConfigTopic": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/MahsaNetConfigTopic.yaml",
        "ebrasha lite": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ebrasha/lite.yaml",
        "FreedomGuard Finder config": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/FreedomGuard/Finder_configs.yaml",
        "rayan_proxy": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/rayan_proxy.yaml",
        "roosterkid": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/roosterkid.yaml",
        "darkvpn": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/darkvpn.yaml",
        "itsyebekhe IR": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/itsyebekhe/IR.yaml",
        "itsyebekhe mix": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/itsyebekhe/mix.yaml",
        "itsyebekhe reality": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/itsyebekhe/reality.yaml",
        "itsyebekhe xhttp": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/itsyebekhe/xhttp.yaml",
        "Maimengmeng": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/maimengmeng/500.yaml",
        "Maimengmeng AnyTLS": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/maimengmeng/AnyTLS.yaml",
        "arshiacomplus vmess": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/arshiacomplus/v2rayExtractor_vmess.yaml",
        "arshiacomplus ss": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/arshiacomplus/v2rayExtractor_ss.yaml",
        "arshiacomplus trojan": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/arshiacomplus/v2rayExtractor_trojan.yaml",
        "arshiacomplus vless": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/arshiacomplus/v2rayExtractor_vless.yaml",
        "arshiacomplus robinhood": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/arshiacomplus/robinhood.yaml",
        "amiralter lite": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/amiralter_config_lite.yaml",
        "4n0nymou3 config fetcher": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/4n0nymou3/multi-proxy-config-fetcher.yaml",
        "Telegram Eag1e YT": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Telegram_Eag1e_YT.yaml",
        "66.42.50.118": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/66.42.50.118.yaml",
        "Barabama/clashmeta": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Barabama/clashmeta.yaml",
        "Barabama/ndnode": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Barabama/ndnode.yaml",
        "Barabama/nodefree": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Barabama/nodefree.yaml",
        "Barabama/v2rayshare": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Barabama/v2rayshare.yaml",
        "HDYOU": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/HDYOU.yaml",
        "Mosifree-Reality": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Mosifree-Reality.yaml",
        "MrMohebi_under_1500ms": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/MrMohebi_under_1500ms.yaml",
        "Ruk1ng001": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Ruk1ng001.yaml",
        "SnapdragonLee_clash_config_extra_US": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/SnapdragonLee_clash_config_extra_US.yaml",
        "YuanZhang": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/YuanZhang.yaml",
        "anaer": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/anaer.yaml",
        "clashe.eu.org": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/clashe.eu.org.yaml",
        "ermaozi": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ermaozi.yaml",
        "fast.lycorisrecoil.org": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/fast.lycorisrecoil.org.yaml",
        "firefoxmmx2": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/firefoxmmx2.yaml",
        "free18": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/free18.yaml",
        "lagzian/meta": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/lagzian/meta.yaml",
        "lagzian/mix": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/lagzian/mix.yaml",
        "lagzian/reality": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/lagzian/reality.yaml",
        "lagzian/trinity": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/lagzian/trinity.yaml",
        "lagzian/vmess": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/lagzian/vmess.yaml",
        "lagzian/vmess_tvc": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/lagzian/vmess_tvc.yaml",
        "liketolivefree": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/liketolivefree.yaml",
        "mfuu": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/mfuu.yaml",
        "moneyfly1/merged_proxies": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/moneyfly1/merged_proxies.yaml",
        "moneyfly1/merged_proxies_new": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/moneyfly1/merged_proxies_new.yaml",
        "moneyfly1/merged_warp_proxies": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/moneyfly1/merged_warp_proxies.yaml",
        "moneyfly1/merged_warp_proxies_new": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/moneyfly1/merged_warp_proxies_new.yaml",
        "peasoft.list/meta": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/peasoft.list/meta.yaml",
        "peasoft.list/yaml": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/peasoft.list/yaml",
        "proxypool.link": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/proxypool.link.yaml",
        "pxypool.131433": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/pxypool.131433.yaml",
        "ripaojiedian": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ripaojiedian.yaml",
        "ronghuaxueleng/NoMoreWalls": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ronghuaxueleng/NoMoreWalls.yaml",
        "ronghuaxueleng/cfmem": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ronghuaxueleng/cfmem.yaml",
        "ronghuaxueleng/combine": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ronghuaxueleng/combine.yaml",
        "ronghuaxueleng/pawdroid": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ronghuaxueleng/pawdroid.yaml",
        "snakem982-clash/meta-2": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/snakem982-clash/meta-2.yaml",
        "snakem982-clash/meta": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/snakem982-clash/meta.yaml",
        "ts-sf": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ts-sf.yaml",
        "tt.vg": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/tt.vg.yaml",
        "An0nymousTeam": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/%40An0nymousTeam.yaml",
        "DarkVPNpro2.txt": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/%40DarkVPNpro2.txt.yaml",
        "FREE2CONFIG_Vless.txt": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/%40FREE2CONFIG_Vless.txt.yaml",
        "proxy_kafee.txt": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/%40proxy_kafee.txt.yaml",
        "redfree8": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/%40redfree8.yaml",
        "v2ray_hidify.txt": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/%40v2ray_hidify.txt.yaml",
        "v2raybluecrystal": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/%40v2raybluecrystal.yaml",
        "Ashkan-m": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Ashkan-m.yaml",
        "Epodonios": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Epodonios.yaml",
        "Everyday-VPN": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Everyday-VPN.yaml",
        "Leon406-hysteria2": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Leon406-hysteria2.yaml",
        "Mosifree/RealityMosifree_Reality": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Mosifree/RealityMosifree_Reality.yaml",
        "Mosifree/SS": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Mosifree/SS.yaml",
        "Mosifree/T%252CH": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Mosifree/T%25252CH.yaml",
        "Mosifree/Vless": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Mosifree/Vless.yaml",
        "Mosifree/Vmess": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Mosifree/Vmess.yaml",
        "NiREvil_SSTime": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/NiREvil_SSTime.yaml",
        "Rayan-Config/ALL": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Rayan-Config/ALL.yaml",
        "Rayan-Config/H-I": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Rayan-Config/H-I.yaml",
        "Rayan-Config/H-II": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Rayan-Config/H-II.yaml",
        "Rayan-Config/H-III": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Rayan-Config/H-III.yaml",
        "Rayan-Config/H-IV": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Rayan-Config/H-IV.yaml",
        "Rayan-Config/H-V": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Rayan-Config/H-V.yaml",
        "Rayan-Config/WG": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Rayan-Config/WG.yaml",
        "ResistalProxy_server": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ResistalProxy_server.yaml",
        "ShadowsocksM-MCI-Wifi": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ShadowsocksM-MCI-Wifi.yaml",
        "Surfboardv2ray/IR": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Surfboardv2ray/IR.yaml",
        "Surfboardv2ray/US": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Surfboardv2ray/US.yaml",
        "Surfboardv2ray/bugfix": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Surfboardv2ray/bugfix.yaml",
        "Surfboardv2ray/ipv6": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Surfboardv2ray/ipv6.yaml",
        "Surfboardv2ray/mahsa": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Surfboardv2ray/mahsa.yaml",
        "Surfboardv2ray/random": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Surfboardv2ray/random.yaml",
        "Surfboardv2ray/udp": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Surfboardv2ray/udp.yaml",
        "YuanZhang.v2ray": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/YuanZhang.v2ray.yaml",
        "amirparsaxs@xsfilternet": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/amirparsaxs%40xsfilternet.yaml",
        "freedomnet25500/free": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/freedomnet25500/free.yaml",
        "freedomnet25500/ss": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/freedomnet25500/ss.yaml",
        "hamedp-71/_openproxylist": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/hamedp-71/_openproxylist.yaml",
        "hamedp-71/hp": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/hamedp-71/hp.yaml",
        "hfarahani_pr": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/hfarahani_pr.yaml",
        "iPsycho1/iPsycho": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/iPsycho1/iPsycho.yaml",
        "iPsycho1/iPsycho_Test-Config": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/iPsycho1/iPsycho_Test-Config.yaml",
        "ivuxy.tech": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ivuxy.tech.yaml",
        "joYAQx.mcsslk.xyz": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/joYAQx.mcsslk.xyz.yaml",
        "liketolivefree_sub": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/liketolivefree_sub.yaml",
        "miladtahanian_config": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/miladtahanian_config.yaml",
        "moeinkey_ssh": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/moeinkey_ssh.yaml",
        "muma16fx.netlify.app": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/muma16fx.netlify.app.yaml",
        "ndsphonemy/default": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ndsphonemy/default.yaml",
        "ndsphonemy/hys-tuic": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ndsphonemy/hys-tuic.yaml",
        "ndsphonemy/lt-sub": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ndsphonemy/lt-sub.yaml",
        "ndsphonemy/my": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ndsphonemy/my.yaml",
        "peasoft_list_raw": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/peasoft_list_raw.yaml",
        "qiaomenzhuanfx.netlify.app": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/qiaomenzhuanfx.netlify.app.yaml",
        "rb360full_Reza/2": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/rb360full_Reza/2.yaml",
        "rb360full_Reza/Collection": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/rb360full_Reza/Collection.yaml",
        "robin.nscl.ir": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/robin.nscl.ir.yaml",
        "roosterkid/V2RAY_BASE64": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/roosterkid/V2RAY_BASE64.yaml",
        "roosterkid/V2RAY_RAW": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/roosterkid/V2RAY_RAW.yaml",
        "sDTz6J.absslk.xyz": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/sDTz6J.absslk.xyz.yaml",
        "shabane/merged": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/shabane/merged.yaml",
        "shabane/ss": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/shabane/ss.yaml",
        "shabane/trojan": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/shabane/trojan.yaml",
        "shabane/vmess": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/shabane/vmess.yaml",
        "theGreatPeter_nodes": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/theGreatPeter_nodes.yaml",
        "tristan-deng_MyNodes": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/tristan-deng_MyNodes.yaml",
        "voken100g/online": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/voken100g/online.yaml",
        "voken100g/recent": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/voken100g/recent.yaml",
        "wudongdefeng_list_raw": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/wudongdefeng_list_raw.yaml",
        "xsfilternet.zaya.io": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/xsfilternet.zaya.io.yaml",
        "shadowmere.xyz": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/shadowmere.xyz.yaml"
    },
    
    "کانفیگ میهومو (کلش متا) فقط دی ان اس بدون پروکسی": {
        "shecan": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/shecan.yml",
        "begzar": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/begzar.yml",
        "electro": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/electro.yml",
        "403": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/403.yml",
        "radar game": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/radar.yml",
        "shelter": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/shelter.yml",
        "shelter-mobile": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/shelter-mobile.yml",
        "mix": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/all.yml",
        "controld": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/controld.yml",
        "Level3": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Level3.yml",
        "AD-Blocker": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/AD-Blocker.yml",
        "Adguard": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Adguard.yml",
        "Cloudflare": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Cloudflare.yml",
        "Google": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Google.yml",
        "LagSlayer": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/LagSlayer.yml",
        "LagZero": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/LagZero.yml",
        "NextDNS": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/NextDNS.yml",
        "NTT": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/NTT.yml",
        "OpenDNS": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/OpenDNS.yml",
        "Rethinkdns": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Rethinkdns.yml",
        "Sprintlink": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Sprintlink.yml",
        "Comodo": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Comodo.yml",
        "DNSWatch": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/DNSWatch.yml",
        "NordVPN": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/NordVPN.yml",
        "Quad9": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Quad9.yml",
        "Surfshark": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Surfshark.yml",
        "UltraDNS": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/UltraDNS.yml",
        "Verisign": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Verisign.yml",
        "Yandex": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Yandex.yml",
        "UncensoredDNS": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/UncensoredDNS.yml"
    },

    "لیست انواع دی ان اس": {
        "Aggregated: all": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/all.txt",
        "Aggregated: doh": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/doh.txt",
        "Aggregated: dot": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/dot.txt",
        "Aggregated: doq": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/doq.txt",
        "Aggregated: doh3": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/doh3.txt",
        "Aggregated: dnscrypt": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/dnscrypt.txt",
        "Aggregated: ipv4": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/ipv4.txt",
        "Aggregated: ipv6": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/ipv6.txt",
        "Aggregated: tcp": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/tcp.txt",
        "Aggregated: udp": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/udp.txt",
        "Aggregated: adblock": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/adblock.txt",
        "Aggregated: malware": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/malware.txt",
        "Aggregated: family": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/family.txt",
        "Aggregated: unfiltered": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/unfiltered.txt",
        "Aggregated: no_log": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/no_log.txt",
        "Aggregated: dnssec": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/dnssec.txt",
        "Aggregated: dns64": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/dns64.txt",
        "DNSCrypt: all": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSCrypt/all.txt",
        "DNSCrypt: adblock": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSCrypt/adblock.txt",
        "DNSCrypt: dnscrypt": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSCrypt/dnscrypt.txt",
        "DNSCrypt: dnssec": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSCrypt/dnssec.txt",
        "DNSCrypt: family": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSCrypt/family.txt",
        "DNSCrypt: malware": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSCrypt/malware.txt",
        "DNSCrypt: no_log": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSCrypt/no_log.txt",
        "DNSCrypt: unfiltered": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSCrypt/unfiltered.txt",
        "Paulmillr: all": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Paulmillr/all.txt",
        "Paulmillr: adblock": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Paulmillr/adblock.txt",
        "Paulmillr: doh": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Paulmillr/doh.txt",
        "Paulmillr: dot": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Paulmillr/dot.txt",
        "Paulmillr: family": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Paulmillr/family.txt",
        "Paulmillr: malware": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Paulmillr/malware.txt",
        "Paulmillr: unfiltered": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Paulmillr/unfiltered.txt",
        "Blacklantern: all": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Blacklantern/all.txt",
        "Blacklantern: ipv4": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Blacklantern/ipv4.txt",
        "Blacklantern: tcp": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Blacklantern/tcp.txt",
        "Blacklantern: udp": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Blacklantern/udp.txt",
        "MutinSA: all": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/MutinSA/all.txt",
        "MutinSA: dns64": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/MutinSA/dns64.txt",
        "MutinSA: dnssec": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/MutinSA/dnssec.txt",
        "MutinSA: ipv4": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/MutinSA/ipv4.txt",
        "MutinSA: ipv6": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/MutinSA/ipv6.txt",
        "MutinSA: unfiltered": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/MutinSA/unfiltered.txt",
        "AdGuard: all": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/AdGuard/all.txt",
        "AdGuard: adblock": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/AdGuard/adblock.txt",
        "AdGuard: dnscrypt": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/AdGuard/dnscrypt.txt",
        "AdGuard: doh": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/AdGuard/doh.txt",
        "AdGuard: doq": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/AdGuard/doq.txt",
        "AdGuard: dot": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/AdGuard/dot.txt",
        "AdGuard: family": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/AdGuard/family.txt",
        "AdGuard: ipv4.": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/AdGuard/ipv4.txt",
        "AdGuard: ipv6": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/AdGuard/ipv6.txt",
        "AdGuard: malware": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/AdGuard/malware.txt",
        "AdGuard: unfiltered": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/AdGuard/unfiltered.txt",
        "Mullvad: all": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Mullvad/all.txt",
        "Mullvad: adblock": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Mullvad/adblock.txt",
        "Mullvad: dnssec": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Mullvad/dnssec.txt",
        "Mullvad: doh": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Mullvad/doh.txt",
        "Mullvad: dot": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Mullvad/dot.txt",
        "Mullvad: family": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Mullvad/family.txt",
        "Mullvad: ipv4": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Mullvad/ipv4.txt",
        "Mullvad: ipv6": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Mullvad/ipv6.txt",
        "Mullvad: malware": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Mullvad/malware.txt",
        "Mullvad: no_log": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Mullvad/no_log.txt",
        "Mullvad: unfiltered": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Mullvad/unfiltered.txt",
        "DNSPrivacyOrg: all": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSPrivacyOrg/all.txt",
        "DNSPrivacyOrg: adblock": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSPrivacyOrg/adblock.txt",
        "DNSPrivacyOrg: dnssec": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSPrivacyOrg/dnssec.txt",
        "DNSPrivacyOrg: doh": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSPrivacyOrg/doh.txt",
        "DNSPrivacyOrg: doq": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSPrivacyOrg/doq.txt",
        "DNSPrivacyOrg: dot": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSPrivacyOrg/dot.txt",
        "DNSPrivacyOrg: malware": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSPrivacyOrg/malware.txt",
        "DNSPrivacyOrg: no_log": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSPrivacyOrg/no_log.txt",
        "DNSPrivacyOrg: unfiltered": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/DNSPrivacyOrg/unfiltered.txt",
        "Curl: all": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Curl/all.txt",
        "Curl: adblock": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Curl/adblock.txt",
        "Curl: dnssec": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Curl/dnssec.txt",
        "Curl: doh": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Curl/doh.txt",
        "Curl: doh3": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Curl/doh3.txt",
        "Curl: doq": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Curl/doq.txt",
        "Curl: dot": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Curl/dot.txt",
        "Curl: family.": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Curl/family.txt",
        "Curl: malware": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Curl/malware.txt",
        "Curl: no_log": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Curl/no_log.txt",
        "Curl: unfiltered": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Curl/unfiltered.txt",
        "Thiagozs: all": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Thiagozs/all.txt",
        "Thiagozs: adblock": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Thiagozs/adblock.txt",
        "Thiagozs: dnssec": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Thiagozs/dnssec.txt",
        "Thiagozs: doh": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Thiagozs/doh.txt",
        "Thiagozs: family": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Thiagozs/family.txt",
        "Thiagozs: malware": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Thiagozs/malware.txt",
        "Thiagozs: no_log": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Thiagozs/no_log.txt",
        "Thiagozs: unfiltered": "https://github.com/10ium/Public-DNS-Collector/raw/main/lists/sources/Thiagozs/unfiltered.txt"
    }
};
